import type { Metadata } from "next"
import { Noto_Sans_KR } from "next/font/google"
import "@styles/reset.css"
import "@styles/color.css"
import Header from "@/components/header/header"

const NotoSansKR = Noto_Sans_KR({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <div id="backdrop-root"></div>
        <div id="modal-root"></div>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
